Frequency <- c(0.6, 0.3, 0.4, 0.4, 0.2, 0.6, 0.3, 0.4, 0.9, 0.2)
BP <- c(103, 87, 32, 42, 59, 109, 78, 205, 135, 176)
First <- c(1, 1, 1, 1, 0, 0, 0, 0, NA, 1)
Second <- c(0, 0, 1, 1, 0, 0, 1, 1, 1, 1)
FinalDecision <- c(0, 1, 0, 1, 0, 1, 0, 1, 1, 1)
PatientData <- data.frame(Frequency, BP, First, Second, FinalDecision)
PatientData
str(PatientData)
boxplot(PatientData$BP)
boxplot(PatientData$First)
boxplot(PatientData$Second)
boxplot(PatientData$FinalDecision)
boxplot(PatientData$BP~PatientData$FinalDecision)
boxplot(PatientData$BP~PatientData$First)
boxplot(PatientData$BP~PatientData$Second)
BP
hist(BP)
hist(BP, breaks = 10, main="With breaks = 10")
hist(BP[First=="0"])
hist(BP[Second=="0"])
hist(BP[FinalDecision=="0"])
hist(BP[FinalDecision=="1"])
library(Hmisc)
hist.data.frame(PatientData)
class(First)
